version: '3.8'
services:
  shadow-bot:
    build: .
    image: shadow-bot:latest
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: 4
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
