name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-bird:
    name: deploy-bird
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: login to docker
        run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image
        run: |
          docker build --tag docker.pkg.github.com/callieve/bird-bot/bird:${{ github.sha }} .
          docker image tag docker.pkg.github.com/callieve/bird-bot/bird:${{ github.sha }} docker.pkg.github.com/callieve/bird-bot/bird:latest

      - name: Push image to Docker Hub
        run: |
          docker push docker.pkg.github.com/callieve/bird-bot/bird:${{ github.sha }}
          docker push docker.pkg.github.com/callieve/bird-bot/bird:latest

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-okto > $GITHUB_WORKSPACE/.kubeconfig

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig -n discord-bots set image statefulset/stateful-bird-bot bird-handler=docker.pkg.github.com/callieve/bird-bot/bird:${{ github.sha }}
          kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig -n discord-bots delete pod -l app=BirdBot
